Vagrant.configure("2") do |config|

    # Choix OS
    config.vm.box = "bento/ubuntu-22.04"
    
    # Network
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.network "forwarded_port", guest: 80, host: 8091
    config.vm.network "forwarded_port", guest: 443, host: 8092
    config.vm.network "forwarded_port", guest: 22, host: 8093
    config.vm.network "forwarded_port", guest: 8080, host: 8094

    # Définit le nom d'hôte de la machine
    config.vm.hostname = "gitlab.local"
    
    # Script Shell
    config.vm.provision "shell", path: "scripts/install_gitlab.sh"
  
  end