# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-22.04"
  
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.network "forwarded_port", guest: 80, host: 8090

    # Définit le nom d'hôte de la machine
    config.vm.hostname = "wordpress.local"
  
    #config.vm.provider "virtualbox" do |vb|
    #  vb.memory = "2048"
    #  vb.cpus = "2"
    #end
  
    config.vm.provision "shell", path: "scripts/install_wordpress.sh"
    config.vm.synced_folder "mon-site-wordpress", "/var/www/html"

    config.ssh.insert_key = true
  
  end
  