Vagrant.configure("2") do |config|
    # Définit une machine virtuelle nommée "jenkins"
    config.vm.define "jenkins" do |jenkins|
  
      # Utilise la boîte de base Ubuntu Focal 64 bits (version LTS)
      jenkins.vm.box = "bento/ubuntu-22.04"
  
      config.vm.provision "shell", path: "scripts/install_jenkins.sh"
      
      # Configure le réseau : réseau privé et port forwardé

      jenkins.vm.network "private_network", ip: "192.168.33.10"
      #port jenkins 8080
      #port sur le hsot 8081
      jenkins.vm.network "forwarded_port", guest: 8080, host: 8081
  
      # Définit le nom d'hôte de la machine
      jenkins.vm.hostname = "jenkins.local"
    end
end